#!/bin/bash

### BEGIN INIT INFO
# Provides: init_gps
# Required-Start: $all
# Required-Stop:
# Default-Start: 4
# Default-Stop:
# Short-Description: Initialises gpsd and python services.
# Description: This file initts all gps related stuff.
### END INIT INFO
(
sleep 60
gpsd /dev/ttyAMA0 -F /var/run/gpsd.sock

(
while : ; do
   chmod 777 /dev/ttyAMA0
   sleep 20
done
) &

sudo -u pi /home/pi/gps_bundle_services start
) > /home/pi/gpsout
